'use client'
import {AlertTriangle,ChevronLeft,Hospital,Lock,RotateCcw,Volume2,Headphones} from 'lucide-react'
import {useKioskStore} from '../../lib/store';import {Button} from './ui'
const t:any={English:{private:'Private session',help:'Staff Help',restart:'Restart',back:'Back',continue:'Continue',finish:'Finish Session',step:'Step',of:'of',audio:'Audio guidance is available'},'हिंदी':{private:'निजी सत्र',help:'स्टाफ सहायता',restart:'फिर से शुरू करें',back:'पीछे',continue:'आगे बढ़ें',finish:'सत्र समाप्त करें',step:'चरण',of:'में से',audio:'हर प्रश्न के लिए ऑडियो मार्गदर्शन उपलब्ध है'},'ગુજરાતી':{private:'ખાનગી સત્ર',help:'સ્ટાફ મદદ',restart:'ફરી શરૂ કરો',back:'પાછળ',continue:'આગળ વધો',finish:'સત્ર પૂર્ણ કરો',step:'પગલું',of:'માંથી',audio:'દરેક પ્રશ્ન માટે ઓડિયો માર્ગદર્શન ઉપલબ્ધ છે'}}
export const copy=(lang:any)=>(t[lang]||t.English)
export function KioskHeader(){const {lang,set,reset}=useKioskStore();const c=copy(lang);return <header className="kiosk-header"><div className="flex items-center gap-4"><div className="brand-mark"><Hospital size={34}/></div><div><div className="brand-name">MediKiosk</div><div className="brand-sub">Patient Clinical Intake • OPD Terminal 04</div></div></div><div className="header-actions"><div className="privacy"><Lock size={18}/>{c.private}</div><select aria-label="Language" value={lang} onChange={e=>set({lang:e.target.value as any})} className="language-select"><option>English</option><option>हिंदी</option><option>ગુજરાતી</option></select><Button variant="danger" className="!min-h-14 !h-14 !px-5 !text-[17px]" onClick={()=>alert(lang==='ગુજરાતી'?'સ્ટાફને મદદ માટે વિનંતી મોકલવામાં આવી છે.':lang==='हिंदी'?'स्टाफ को मदद के लिए बुलाया गया है।':'A staff member has been requested.' )}><AlertTriangle size={21}/>{c.help}</Button><button onClick={reset} className="restart" aria-label={c.restart}><RotateCcw/></button></div></header>}
export function Progress(){const {step,lang}=useKioskStore();const c=copy(lang);return <div className="progress-bar"><div className="progress-inner"><div className="progress-track"><div className="progress-fill" style={{width:`${(step/8)*100}%`}}/></div><span>{c.step} {step+1} {c.of} 9</span></div></div>}
export function BottomBar(){const {step,back,next,consent,identity,inputMode,presentComplaint,presentValid,pastValid}=useKioskStore();const lang=useKioskStore(s=>s.lang);const c=copy(lang);let disabled=false;if(step===2)disabled=!consent;if(step===3)disabled=!identity;if(step===4){if(inputMode==='touch'){disabled=!(presentValid||pastValid);}else if(inputMode==='voice')disabled=false;else disabled=true;}const hideContinue=[0,1,2,3,5].includes(step);return <footer className="bottom-bar"><div className="bottom-inner"><Button variant="secondary" disabled={step===0} onClick={back} className="min-w-[150px]"><ChevronLeft/>{c.back}</Button>{!hideContinue&&(step<8?<Button disabled={disabled} onClick={next} className="min-w-[190px]">{c.continue}<span>→</span></Button>:<Button onClick={()=>useKioskStore.getState().reset()} className="min-w-[220px]">{c.finish}</Button>)}</div></footer>}
export function StaffHelp(){return null}
